@startuml
left to right direction

actor "Відвідувач" as user
actor "Адміністратор" as admin
actor "Тренер" as pesonal 

user --> (Перегляд вправ)
user --> (Авторизація)
(Авторизація) <-- (Вхід): <<include>>
(Авторизація) <-- (Реєстрація): <<include>>

admin --> (Додавання вправ)
admin --> (Назначення тренерів)
admin --> (Створення вправ)
admin --> (Авторизація)

pesonal --> (Призначення тренувань)
pesonal --> (Перегляд тренувань)
pesonal  --> (Авторизація)


@enduml
