@startuml

node "Docker Compose" as Server {
    [PostgreSQL]
    [Nginx]

    component "Python AI" as Python {
     () "main.py"
    } 
    component "Rust Main" as Rust {
     () "main.rs"
    }
}

[Nginx] --> [Rust]: HTTP
[Nginx] --> [Python]: HTTP
[Rust] --> [PostgreSQL]: TCP/IP
[Python] --> [PostgreSQL]: TCP/IP

component "Web Browser" as Web {
    () "main.dart"
}

component "Mobile phone" as Phone {
    () "Main.apk"
}

component "Smart device" as IoT {
    () "lib.rs"
}

IoT -- Nginx: HTTPS
Web -- Nginx: HTTPS
Phone -- Nginx: HTTPS

@enduml
