@startuml
skinparam defaultTextAlignment center

[*] --> Очікування : Запуск
Очікування --> Налаштування : Оновити\nналаштування
Налаштування --> Очікування : Отримати\nтокен
Очікування --> Тренування : Почати\nтренування
Тренування --> Аналіз : Отримати\nдані
Аналіз --> Тренування : Показати\nрекомендацію
Аналіз --> Завершено : Завершити\nтренування
Завершено --> [*] : Вихід


Очікування : Показ опцій
Очікування : Вибір дії

Налаштування : Реєстрація
Налаштування : ID пристрою

Тренування : Поточна вправа
Тренування : Тривалість
Тренування : Пульс

@enduml
