@startuml
actor Admin as "Адмін"
actor Personal as "Тренер"

left to right direction

Admin --> (Керування тренерами)
(Керування тренерами) <-- (Перегляд інформації про тренера): <<include>>

Personal --> (Керування клієнтами)
(Керування клієнтами) <-- (Перегляд інформації про клієнта): <<include>>

Personal --> (Створення занять)
(Створення занять) <-- (Перегляд інформації про заняття): <<include>>
(Створення занять) <-- (Додавати клієнтів на заняття): <<include>>


Admin --> (Керування системою)
(Керування системою) -- (Видалення даних): <<include>>
(Керування системою) -- (Створення нових типів занять): <<include>>

Personal --> (Вхід до системи)
Admin --> (Вхід до системи)


@enduml
