@startuml
actor Admin as "Адмін"
actor Personal as "Тренер"

left to right direction

Admin -- (Керування тренерами)
(Керування тренерами) -- (Додавання тренера)
(Керування тренерами) -- (Видалення тренера)
(Керування тренерами) -- (Редагування тренера)
(Керування тренерами) -- (Перегляд інформації про тренера)

Personal -- (Керування клієнтами)
(Керування клієнтами) -- (Додавання клієнта)
(Керування клієнтами) -- (Видалення клієнта)
(Керування клієнтами) -- (Редагування клієнта)
(Керування клієнтами) -- (Перегляд інформації про клієнта)

Personal -- (Створення занять)
(Створення занять) -- (Додавання заняття)
(Створення занять) -- (Видалення заняття)
(Створення занять) -- (Редагування заняття)
(Створення занять) -- (Перегляд інформації про заняття)
(Створення занять) -- (Додавати клієнтів на заняття)
(Створення занять) -- (Видаляти клієнтів з заняття)

Personal -- (Перегляд статистики)
(Перегляд статистики) -- (Перегляд статистики клієнтів)
(Перегляд статистики) -- (Перегляд статистики тренерів)

Admin -- (Керування абонементами)
(Керування абонементами) -- (Додавання абонементу)
(Керування абонементами) -- (Видалення абонементу)
(Керування абонементами) -- (Редагування абонементу)
(Керування абонементами) -- (Перегляд інформації про абонемент)

Admin -- (Керування системою)
(Керування системою) -- (Створення резервних копій)
(Керування системою) -- (Відновлення з резервної копії)
(Керування системою) -- (Видалення даних)

Personal -- (Вхід до системи)
Admin -- (Вхід до системи)


@enduml
