@startuml
start

if(Чи існує користувач) then (Так)
  :Вхід;
else (Ні)
  :Реєстрація;
endif

rectangle "Авторизований" as User {
    :Вибір мови;
    :Вибір типу входу;
    :Створення тренерів;
    :Створення завдань;
}

@enduml
