@startuml

start

if (Чи існує користувач) then (так)
  :Вхід;
else (ні)
  :Реєстрація;
endif

package "Користувач" {
    :Перегляд списку заннять;
    :Прив'язка IoT пристрою;
    :Вибір заняття;
}

stop

@enduml
