@startuml

left to right direction

actor "Користувач" as User

User --> (Авторизація)
(Авторизація) <-- (Вхід) : <<include>>
(Авторизація) <-- (Реєстрація) : <<include>>

User --> (Перегляд вправ)
(Перегляд вправ) <-- (Прив'язка для IoT) : <<include>>

User --> (Прив'язка IoT для облікового запису)

@enduml
